# Service configuration
service:
  host: HOST_NAME
  port: SERVICE_PORT
  baseUrl: SERVICE_BASE_URL

# Database configuration
postgres:
  host: POSTGRES_HOST
  port: POSTGRES_PORT
  username: POSTGRES_USERNAME
  password: POSTGRES_PASSWORD
  database: POSTGRES_DATABASE
  schema: POSTGRES_SCHEMA

# API documentation configuration
api-docs:
  username: API_DOCS_USERNAME
  password: API_DOCS_PASSWORD

# Log configuration
log:
  level: LOG_LEVEL
