# Service config
service:
  host: 127.0.0.1
  port: 3031
  baseUrl: /api/v1

# Database configuration
mongodb:
  uri: mongodb://localhost:27017/lirest

# Swagger username and password
api-docs:
  username: ''
  password: ''

# Log configuration
log:
  level: info